---
title: "Programming_Lab_2"
author: "Zivanic, Lugli, Battaglio"
format: html
editor: visual
---

#Gender equality in the work place

{r}
library(readr)
library(tidyverse)
library(gapminder)
library(ggplot2)
library(dplyr)
library(knitr)
library(broom)
library(magrittr)
library(knitr)
library(plotly)

getwd()
setwd("/Users/chiarazivanic/Desktop/Programminglab2")
paygapEU <- read.csv("pay_gap_Europe.csv")

head(paygapEU)
summary(paygapEU$GDP)
paygap <- paygapEU |> filter(Country %in% c("Italy", "Switzerland", "Bulgaria")) 
paygap <- paygap |> select(-c(Industry, Electricity_supply, Water_supply, Retail.trade, Transportation, Accommodation, Information, Financial, Professional_scientific, Administrative, Public_administration, Human_health, Arts, Other))

paygap <- paygap |> mutate(Secondary_sector = rowMeans(select(paygap, Construction, Mining, Manufacturing), na.rm=TRUE))

# Esegui la regressione lineare generale 
lin_mod1 <- lm(Secondary_sector ~ GDP, data = paygap)
lin_mod1

# Crea il grafico utilizzando ggplot2
ggplot(paygap, aes(x = GDP, y = Secondary_sector, color = Country)) +
  geom_point(alpha = 0.5) +  
  geom_smooth(data = paygap, method = "lm", se = TRUE, aes(fill = Country), alpha = 0.2) +  # Linee di regressione con intervalli di confidenza
  geom_line(data = data.frame(GDP = unique(paygap$GDP), predictions = predict(lin_mod1, newdata = data.frame(GDP = unique(paygap$GDP)))), 
            aes(x = GDP, y = predictions), color = "black", size = 1) +  # Linea di regressione generale
  labs(title = "Regressione di Secondary_sector su GDP",
       x = "GDP",
       y = "Secondary Sector") +
  theme_minimal()

summary(lin_mod1)

